- name: Install bridge-utils
  ansible.builtin.apt:
    name: bridge-utils
- name: Create /etc/network/interfaces.d directory
  ansible.builtin.file:
    path: /etc/network/interfaces.d
    state: directory
    mode: "0755"
- name: Write network interfaces configuration
  notify:
    - Reload interfaces
  ansible.builtin.template:
    src: etc/network/interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    mode: "0644"
