- name: Install dnsmasq
  ansible.builtin.apt:
    package: dnsmasq
- name: Create /etc/dnsmasq.conf.d directory
  ansible.builtin.file:
    path: /etc/dnsmasq.conf.d
    state: directory
    mode: "0755"
- name: Write dnsmasq configuration
  notify:
    - Reload dnsmasq
  ansible.builtin.copy:
    src: etc/dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    mode: "0644"
- name: Enable dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true
