- name: Install libvirt
  ansible.builtin.apt:
    package:
      - libvirt-clients
      - libvirt-daemon-system
      - qemu-system
      - qemu-utils
      - virtinst
      - ovmf
    install_recommends: false
